// Generated by scripts/build-data.mjs from agent-demos/kimi-k3-readability-test/samples — do not edit.
// All sample texts are MOCK data.
export type Sample = { id: string; title: string; level: string; text: string }
export const SAMPLES: Sample[] = [
  {
    "id": "sample-1-simple",
    "title": "The River Trip",
    "level": "Simple narrative · ~grade 4",
    "text": "MOCK SAMPLE — written for this demo. Level: simple (roughly grade 4).\n\nThe River Trip\n\nSam had a small red boat. He kept it by the river near his house. On Saturday, the sun was warm and the water was calm. Sam asked his friend Ada to come with him.\n\nThey put on their life jackets. Sam's mum gave them a bag with bread, cheese and two apples. \"Be back before tea,\" she said.\n\nThe boat moved slowly down the river. They saw a heron standing on one leg. They saw fish jump out of the water. Ada trailed her hand in the cool river and laughed.\n\nWhen the wind grew strong, Sam pulled the boat to the bank. They ate their lunch under a willow tree. Then they rowed home, tired and happy.\n"
  },
  {
    "id": "sample-2-general",
    "title": "How Compost Works",
    "level": "General explainer · ~grade 7–8",
    "text": "MOCK SAMPLE — written for this demo. Level: general audience (roughly grade 7–8).\n\nHow Compost Works\n\nA compost heap turns kitchen scraps into food for your garden. It is not magic. It is the work of millions of tiny living things, and you can help them do it well.\n\nWhat to put in\n\nCompost needs two kinds of material. \"Greens\" are wet things like vegetable peelings, grass cuttings and coffee grounds. \"Browns\" are dry things like cardboard, dead leaves and straw. Aim for roughly two parts brown to one part green. This balance gives the microbes both energy and air.\n\nWhat happens inside\n\nBacteria and fungi break the material down. As they work, the heap warms up. A warm heap is a healthy heap. Worms and beetles join in later and chew the scraps into smaller pieces.\n\nHow to help it along\n\nTurn the heap every few weeks so air can reach the middle. Keep it as damp as a wrung-out sponge. If it smells bad, add more browns. If nothing is happening, add more greens and a little water.\n\nAfter six to twelve months you will have dark, crumbly compost. Spread it on your beds in spring and your plants will thank you for it.\n"
  },
  {
    "id": "sample-3-academic",
    "title": "Urban Heat Islands",
    "level": "Academic abstract · ~grade 13+",
    "text": "MOCK SAMPLE — written for this demo. Level: academic abstract (roughly grade 13+).\n\nThermal Stratification and the Urban Heat Island Effect: A Synthesis\n\nAbstract\n\nThe urban heat island phenomenon, whereby metropolitan regions exhibit elevated ambient temperatures relative to their rural peripheries, constitutes a significant confounding variable in climatological assessments and a considerable determinant of municipal energy consumption. This paper synthesises contemporary empirical investigations into the thermodynamic mechanisms underlying nocturnal heat retention in densely constructed environments, with particular emphasis upon the radiative properties of anthropogenic materials, the attenuation of convective cooling attributable to canyon geometry, and the diminution of evaporative regulation consequent upon vegetation removal.\n\nThe evidence indicates that mitigation strategies incorporating high-albedo surfaces, extensive green infrastructure, and hydrological restoration can achieve measurable temperature reductions; however, the heterogeneity of urban morphologies necessitates locally calibrated interventions rather than universally applicable prescriptions. Furthermore, the disproportionate exposure of socioeconomically disadvantaged populations to extreme thermal conditions introduces an equity dimension that conventional cost-benefit frameworks frequently fail to accommodate. We conclude by delineating methodological limitations in extant comparative studies and proposing a standardised protocol for longitudinal thermal monitoring across heterogeneous urban typologies.\n"
  },
  {
    "id": "sample-4-bureaucratic",
    "title": "Stationery Memorandum",
    "level": "Officialese · deliberately dense",
    "text": "MOCK SAMPLE — written for this demo. Level: bureaucratic officialese (deliberately poor readability).\n\nMEMORANDUM — Interim Provisions for the Rationalisation of Stationery Procurement\n\nPursuant to the aforementioned deliberations of the Facilities Optimisation Sub-Committee, and in accordance with the utilisation review undertaken during the preceding fiscal period, all personnel are hereby notified that the requisition of consumable office supplies shall henceforth be subject to a centralised authorisation procedure prior to the submission of any procurement request.\n\nIt is incumbent upon line managers to undertake a comprehensive verification of existing inventory holdings prior to the approval of additional requisitions, in order that unnecessary duplication of expenditure may be precluded. Failure to adhere to the prescribed procedure may result in the rejection of the request and the requirement for resubmission in the subsequent monthly cycle.\n\nIn the event that exceptional circumstances necessitate the expedited acquisition of materials, an exemption application may be submitted to the Procurement Rationalisation Officer, accompanied by appropriate justification documentation, for consideration at the earliest available opportunity, although it should be noted that the submission of such an application does not constitute a guarantee that authorisation will be forthcoming.\n\nYour cooperation in the implementation of these provisions is appreciated.\n"
  }
]
