#!/usr/bin/env node
// Generates src/renderer/src/analysis/wordlists.ts and samples.ts from the
// agent-demos readability tool (the provenance source). Re-run after the demo's
// word lists or samples change.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { homedir } from 'node:os'

const DEMO = join(homedir(), 'agent-demos/kimi-k3-readability-test')
const OUT = join(dirname(fileURLToPath(import.meta.url)), '../src/renderer/src/analysis')

// wordlists: demo data/wordlists.js holds two `const X = new Set([...])` lines.
const wl = readFileSync(join(DEMO, 'data/wordlists.js'), 'utf8')
const daleChall = JSON.parse(wl.match(/DALE_CHALL_WORDS = new Set\((\[.*?\])\);/s)[1])
const awl = JSON.parse(wl.match(/AWL_WORDS = new Set\((\[.*?\])\);/s)[1])

writeFileSync(
  join(OUT, 'wordlists.ts'),
  `// Generated by scripts/build-data.mjs from agent-demos/kimi-k3-readability-test — do not edit.
// Sources: Dale-Chall familiar word list (1948); Academic Word List (Coxhead, 2000).
export const DALE_CHALL_WORDS: ReadonlySet<string> = new Set(${JSON.stringify(daleChall)})
export const AWL_WORDS: ReadonlySet<string> = new Set(${JSON.stringify(awl)})
`
)

const META = {
  'sample-1-simple': ['The River Trip', 'Simple narrative · ~grade 4'],
  'sample-2-general': ['How Compost Works', 'General explainer · ~grade 7–8'],
  'sample-3-academic': ['Urban Heat Islands', 'Academic abstract · ~grade 13+'],
  'sample-4-bureaucratic': ['Stationery Memorandum', 'Officialese · deliberately dense']
}
const samples = readdirSync(join(DEMO, 'samples'))
  .filter((f) => f.endsWith('.txt'))
  .sort()
  .map((f) => {
    const slug = f.replace(/\.txt$/, '')
    const [title, level] = META[slug] ?? [slug, '']
    return { id: slug, title, level, text: readFileSync(join(DEMO, 'samples', f), 'utf8') }
  })

writeFileSync(
  join(OUT, 'samples.ts'),
  `// Generated by scripts/build-data.mjs from agent-demos/kimi-k3-readability-test/samples — do not edit.
// All sample texts are MOCK data.
export type Sample = { id: string; title: string; level: string; text: string }
export const SAMPLES: Sample[] = ${JSON.stringify(samples, null, 2)}
`
)
console.log(`wordlists (${daleChall.length} Dale-Chall, ${awl.length} AWL) + ${samples.length} samples -> ${OUT}`)
